content_access_roles_gids:
  anonymous: 1
  authenticated: 2
  administrator: 3
  driver: 4
  store_owner: 5
  store_customer: 6
  admin: 7
_core:
  default_config_hash: 7LkiviGITIpniIOOIzpuxR7r4XzqqYN_cwu0fb0kx1M
langcode: ar
content_access_node_type:
  shipping_order: 'a:2:{s:8:"view_own";a:1:{i:0;s:13:"authenticated";}s:4:"view";a:6:{i:0;s:13:"authenticated";i:1;s:13:"administrator";i:2;s:6:"driver";i:3;s:11:"store_owner";i:4;s:14:"store_customer";i:5;s:5:"admin";}}'
