favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://localhost/drupal-8/themes/h2h/favicon.ico'
  use_default: 1
schemas:
  bootstrap: 8000
  h2h: 8000
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: ''
  url: ''
  use_default: 1
cdn_jsdelivr_theme: bootstrap_theme
table_responsive: '-1'
table: ''
