<?php

/**
 * @file
 * inv_flickr module
 */

function inv_flickr_theme($existing, $type, $theme, $path) {
    return array(
        'flickr' => array(
            'variables' => array(
                'flickr_source' => '',
                'flickr_id' => '',
                'flickr_num_photo' => '',
                'flickr_display' => '',
                'flickr_image_size' => '',
                'flickr_layout' => '',
            ),
            'template' => 'flickr'
        ),
    );
}