<?php
/**
 * @file
 * Views bxslider style plugin code.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Render\Element\RenderElement;
use Drupal\taxonomy\Entity\Vocabulary;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_preprocess_HOOK
 */
function template_preprocess_views_view_invaccordion(&$variables) {

	$options = $variables ['options'] = $variables ['view']->style_plugin->options;
    $view = $variables['view'];
    $items = array();
    $title_field = $options['title_field'];
	if($options['accordion_filter']){
        $vocab = $options['accordion_filter_vocabulary'];
        $categories = array();
        $terms = \Drupal::entityManager()->getStorage('taxonomy_term')->loadTree($vocab, 0, NULL, false);
        foreach($terms as $term) {
            $categories[Html::getClass($term->name)] = $term->name;
        }
        $variables['categories'] = $categories;
        foreach ($variables['rows'] as $result_index => $item) {
            $title = $variables['view']->style_plugin->getField($result_index, $title_field);
            $items[$result_index]['title'] = $title;
            $items[$result_index]['content'] = $variables['view']->style_plugin->getField($result_index, 'body');;
            $items[$result_index]['class'] = "";
            $nid = $view->result[$result_index]->nid;
            $classes = "";
            foreach(accordion_get_term_by_node_id_vocabulary_id($nid,$vocab) as $termOfNode) {
                $classes .= ' '.Html::getClass($termOfNode->name);
            }
            $items[$result_index]['class'] =  $items[$result_index]['class']. " ".$classes;
        }
        $variables['#attached']['library'] = array('inv_views_accordion/accordion_filter');
    }

    $variables['items'] = $items;
}

function accordion_get_term_by_node_id_vocabulary_id($nid,$vid) {
    $query = db_select('taxonomy_index','tx');
    $query->leftjoin('taxonomy_term_field_data','ttfd', 'tx.tid=ttfd.tid');
    $query->fields('tx',array('tid'));
    $query->fields('ttfd',array('name'));
    $query->condition('tx.nid', $nid);
    $query->condition('ttfd.vid', $vid);
    return $query->execute()->fetchAll();
}
